# Generated by Django 5.0.3 on 2024-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutors_info',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('tut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_stud', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tutors_login',
            fields=[
                ('username', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
