# Generated by Django 5.0.3 on 2024-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_activity_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
