# Generated by Django 5.0.3 on 2024-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_activity_std_name_activity_tut_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='std_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tut_id',
            field=models.IntegerField(),
        ),
    ]
