# Generated by Django 5.0.3 on 2024-04-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('tut_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=30)),
                ('act_points', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=1)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_info')),
            ],
        ),
    ]
