# Generated by Django 5.0.3 on 2024-04-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_stud_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='proof',
            field=models.FileField(null=True, upload_to='josiah'),
        ),
    ]
