# Generated by Django 5.0.3 on 2024-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_info_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_login',
            name='login',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
