# Generated by Django 5.0.3 on 2024-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_stud_login_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_login',
            name='login',
        ),
    ]
